clientApp:
  name: ms-booking

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:ms_booking;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: db
    password: password
    hikari:
      poolName: Hikari
      auto-commit: true
  h2:
    console:
      enabled: false
  jpa:
    show-sql: true
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
    hibernate:
      ddl-auto: create